image:
  repository: registry.gitlab.com/gitlab-org/build/cng/kubectl
  tag: 54033d1192f85dbd4f30e84187818514b5b07ebd
  # pullPolicy: Always
  pullSecrets: []
selfsign:
  image:
    repository: registry.gitlab.com/gitlab-org/build/cng/cfssl-self-sign
    tag: 1.2
  keyAlgorithm: "rsa"
  keySize: "4096"
  expiry: "365d"
  caSubject: "GitLab Helm Chart"
resources: {}

## Support for tolerations for pod scheduling
tolerations: []

env: production
global: {}
enabled: false
serviceAccount:
  create: true
  name: # Specify a pre-existing ServiceAccount name
rbac:
  create: true
resources:
  requests:
    cpu: 50m
securityContext:
  # in debian/alpine based images, this is `nobody:nogroup`
  runAsUser: 65534
  fsGroup: 65534
