apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-admin
  namespace: bdev
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: bdev
  name: gitlab-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: gitlab-admin
  namespace: bdev
subjects:
  - kind: ServiceAccount
    name: gitlab-admin
    namespace: bdev
roleRef:
  kind: Role
  name: gitlab-admin
  apiGroup: rbac.authorization.k8s.io
